const express = require("express");
const path = require("path");
const PDFDocument = require("pdfkit");

const app = express();
const PORT = process.env.PORT || 8080;

// Basic logging
app.use((req, res, next) => {
  const now = new Date().toISOString();
  console.log(`[${now}] ${req.method} ${req.url}`);
  next();
});

// Parse JSON bodies for API routes
app.use(express.json());

// Serve static assets
app.use(express.static(path.join(__dirname, "public")));

// ---- API: Invoice PDF generator ----
app.post("/api/invoice/generate", (req, res) => {
  const {
    from = "",
    to = "",
    number = "",
    amount = 0,
    notes = "",
  } = req.body || {};

  console.log("Generating invoice PDF for:", { from, to, number, amount });

  // Create a PDF document
  const doc = new PDFDocument({ margin: 50 });

  // Set headers so browser downloads it
  const filename = (number || "invoice").replace(/[^\w\-]+/g, "_") + ".pdf";
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="${filename}"`
  );

  // Pipe PDF to response
  doc.pipe(res);

  // Simple invoice layout
  doc
    .fontSize(22)
    .text("INVOICE", { align: "right" })
    .moveDown();

  doc
    .fontSize(10)
    .text("From:", { continued: false })
    .font("Helvetica-Bold")
    .text(from || "—")
    .moveDown(0.5)
    .font("Helvetica")
    .text("Bill To:")
    .font("Helvetica-Bold")
    .text(to || "—")
    .moveDown();

  if (number) {
    doc
      .font("Helvetica")
      .text(`Invoice / Load #: ${number}`)
      .moveDown(0.5);
  }

  const amt = typeof amount === "number" ? amount : parseFloat(amount) || 0;
  const amtStr = amt ? `$${amt.toFixed(2)}` : "—";

  doc
    .font("Helvetica-Bold")
    .text(`Total Due: ${amtStr}`, { align: "right" })
    .moveDown();

  doc
    .font("Helvetica")
    .text("Details / Notes:", { underline: true })
    .moveDown(0.25)
    .font("Helvetica")
    .text(notes || "No additional notes provided.")
    .moveDown(2);

  doc
    .fontSize(9)
    .fillColor("#6b7280")
    .text(
      "Generated by MyFreightTracker PDF Studio. This invoice is for business use between the parties listed above.",
      { align: "center" }
    );

  // Finalize PDF
  doc.end();
});

// Root route – serve main UI
app.get("/", (req, res) => {
  res.sendFile(path.join(__dirname, "public", "index.html"));
});

app.listen(PORT, () => {
  console.log(`DocSuite UI running on port ${PORT}`);
});
